language: node_js
node_js:
  - "8.10"
install: npm ci
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run deploy -- --stage prod
    on:
      branch: master
